### ISSUE TITLE
Do you have workaround to run on Unreal 5.1?

### ISSUE THREAD

**Issue by wkitja** [microsoft/OnnxRuntime-UnrealEngine#7]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/113427468/204141522-91b05c4c-57ab-4ad8-9808-1e131afeb44d.png">

This is the result when I run this project on Unreal 5.1.
Do you have workaround to run on Unreal 5.1?

Thank you in advance.

**Comment by Gabaly92** [comment]
I am having the same issue, any fix for this in UE5.1 ? 

Thank you

**Comment by deezhizyu** [comment]
Change Anti-Aliasing Method in project settings to FXAA

**Comment by Gabaly92** [comment]
Worked, thank you
